name: Terraform Plan

on:
  pull_request:

jobs:
  gcp-vm-dev-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Format
        working-directory: terraform/infrastructure
        run: terraform fmt -check -recursive

      - name: Init
        working-directory: terraform/infrastructure/live/dev/asia-southeast1/gcp-vm
        run: terraform init

      - name: Validate
        working-directory: terraform/infrastructure/live/dev/asia-southeast1/gcp-vm
        run: terraform validate

      - name: Plan
        working-directory: terraform/infrastructure/live/dev/asia-southeast1/gcp-vm
        run: terraform plan
