---
galaxy_info:
  role_name: sonarqube
  author: seang
  description: Install and configure SonarQube.
  min_ansible_version: "2.14"
dependencies:
  - role: venv_bootstrap
    service_config_extra_system_packages:
      - openjdk-17-jdk
      - postgresql
      - postgresql-common
      - postgresql-contrib
      - python3-psycopg2
collections:
  - community.postgresql
