[ceph_nodes]
haproxy-1 ansible_host=130.211.251.49 ip=10.140.0.5 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa
haproxy-2 ansible_host=34.146.72.28 ip=10.146.0.5 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa
haproxy-3 ansible_host=34.84.162.236 ip=10.146.0.4 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa

[nfs_clients]
master01 ansible_host=34.21.181.216 ip=10.148.0.6 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa
master02 ansible_host=34.124.141.97 ip=10.148.0.5 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa
master03 ansible_host=35.187.228.51 ip=10.148.0.4 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa
worker01 ansible_host=35.201.128.109 ip=10.140.0.4 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa
worker02 ansible_host=104.199.205.20 ip=10.140.0.6 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa

[all:vars]
ansible_user=seang
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
