[ceph_nodes]
haproxy-1 ansible_host=34.84.45.214 ip=10.146.0.11 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa
haproxy-2 ansible_host=35.194.124.211 ip=10.146.0.14 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa
haproxy-3 ansible_host=34.84.27.146 ip=10.146.0.12 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa

[nfs_clients]
master01 ansible_host=35.201.236.128 ip=10.140.0.21 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa
master02 ansible_host=35.194.255.144 ip=10.140.0.18 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa
master03 ansible_host=35.236.138.10 ip=10.140.0.14 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa
worker01 ansible_host=34.146.199.238 ip=10.146.0.13 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa
worker02 ansible_host=130.211.251.49 ip=10.140.0.22 ansible_ssh_private_key_file=/home/seang/.ssh/id_rsa

[all:vars]
ansible_user=seang
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
