apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
  labels:
    app.kubernetes.io/name: {{ include "nfs-storage-test.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
